# Generated by Django 5.2.7 on 2025-10-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='song',
            field=models.FileField(blank=True, null=True, upload_to='content/story-music'),
        ),
    ]
