# Generated by Django 5.2.7 on 2025-11-03 05:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_story_options_post_postimages_postmusic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('songName', models.CharField(max_length=400)),
                ('songWriter', models.CharField(max_length=400)),
                ('composer', models.CharField(max_length=400)),
                ('lyricst', models.CharField(max_length=400)),
                ('movie', models.CharField(max_length=400)),
                ('year', models.CharField(max_length=400)),
                ('isAlbum', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='Music')),
            ],
            options={
                'verbose_name': 'Music',
                'verbose_name_plural': 'Musics',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='postimages',
            options={'verbose_name': 'Post Image', 'verbose_name_plural': 'Post Images'},
        ),
        migrations.AlterModelOptions(
            name='postmusic',
            options={'verbose_name': 'Post Music', 'verbose_name_plural': 'Post Musics'},
        ),
        migrations.AlterModelOptions(
            name='storymentions',
            options={'verbose_name': 'Story Mention', 'verbose_name_plural': 'Story Mentions'},
        ),
        migrations.AlterModelOptions(
            name='storymusic',
            options={'verbose_name': 'story music', 'verbose_name_plural': 'story musics'},
        ),
        migrations.RemoveField(
            model_name='story',
            name='song',
        ),
        migrations.AddField(
            model_name='postmusic',
            name='Music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.music'),
        ),
        migrations.AddField(
            model_name='storymusic',
            name='Music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.music'),
        ),
    ]
