# Generated by Django 5.2.7 on 2025-11-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_music_alter_post_options_alter_postimages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Post'),
        ),
    ]
