# Generated by Django 5.2.7 on 2025-11-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authantication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='profile picture'),
        ),
    ]
